package com.gjuhasz86.dupfinder.backend.server

import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import better.files._
import com.gjuhasz86.dupfinder.backend.core.GraphBuilder

import scala.annotation.tailrec
import scala.concurrent.ExecutionContextExecutor
import scala.io.StdIn

// runs a webserver that serves static files from a
// directory given as a command-line argument
// and also serves api calls
// Requires a data/nodes.csv file (generated by the Preparation class)
// as well as a data/hashes.txt file generated by the following command:
// for f in tmp ; do find $f -type f -exec md5sum {} \; > hashes.$f.txt 2>hashes.$f.err ; done
// the file names are hardcoded and can be edited below
object WebServer {
  def main(args: Array[String]): Unit = {
    implicit val system: ActorSystem = ActorSystem()
    implicit val executionContext: ExecutionContextExecutor = system.dispatcher

    val staticPath = args.head

    val graphBuilder = new GraphBuilder("data/nodes.csv".toFile, "data/hashes.txt".toFile)
    println(graphBuilder.root)
    println(graphBuilder.root.path)
    println(graphBuilder.nodesByPath(graphBuilder.root.path).children.map(_.name))

    val bindingFuture = Http().newServerAt("0.0.0.0", 4201).bindFlow(new Routes(staticPath, graphBuilder).route)
    println(s"Server online at http://localhost:4201/\nType 'exit' without quotes and press RETURN to stop...")

    exitLoop()

    bindingFuture
      .flatMap(_.unbind()) // trigger unbinding from the port
      .onComplete(_ => system.terminate()) // and shutdown when done
  }

  @tailrec
  def exitLoop(): Int = {
    val line = StdIn.readLine() // let it run until user presses return
    if (line == "exit") 0 else exitLoop()
  }
}
